version: '3.8'

networks:
  cheese-layer:
    driver: bridge

services:
  sandwich-club-api:
    container_name: sandwich-club-api
    build:
      context: ./
      cache_from:
        - sandwich-club/nx-base
        - nginx:1-alpine
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: sandwich-club/api:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'production'
      port: 4939
    networks:
      - cheese-layer
    restart: on-failure
  sandwich-club-react:
    container_name: sandwich-club-react
    build:
      context: ./
      cache_from:
        - sandwich-club/nx-base
        - node:current
      dockerfile: ./apps/sandwich-club/Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: sandwich-club/react:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'production'
      port: 4900
    networks:
      - cheese-layer
    restart: on-failure
