version: '3.8'

networks:
  cheese-layer:
    driver: bridge

services:
  api-server:
    container_name: api-server
    build:
      context: ./
      cache_from:
        - npm-base:nx-base
        - node:lts-alpine
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: api-server:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'production'
      port: 4939
    networks:
      - cheese-layer
    restart: on-failure
  react-app:
    container_name: react-client
    build:
      context: ./
      cache_from:
        - nginx:1-alpine
      dockerfile: ./apps/sandwich-club/Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: react-app:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'production'
      port: 80
    networks:
      - cheese-layer
    restart: on-failure
